services:
  - type: web
    name: cfg-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    packages:
      - graphviz  # This installs the system-level graphviz package
